package com.example.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Springboot315AutoConfigurationApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext applicationContext = SpringApplication.run(Springboot315AutoConfigurationApplication.class, args);

		// 从IoC容器中查看有多少个组件，将组件的id打印出来
		String[] allBeanNames = applicationContext.getBeanDefinitionNames();
		for (String allBeanName : allBeanNames) {
			System.out.println(allBeanName);
		}

		applicationContext.close();
	}

}
