package com.example.springboot;

import com.example.springboot.bean.AppBean;
import com.example.springboot.bean.User;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;
import org.springframework.boot.context.properties.EnableConfigurationProperties;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
// 第三种：在主入口程序上添加以下注解
 @EnableConfigurationProperties({User.class, AppBean.class})	// 启用 把配置文件中的信息绑定到bean上 的功能

// 第四种方式：在主入口程序上添加以下注解
//@ConfigurationPropertiesScan(basePackages = "com.example.springboot.bean")	// 扫描指定包下的所有类，看看是否有@ConfigurationProperties注解
public class Springboot310ConfigBindToBeanApplication {

	public static void main(String[] args) {
		SpringApplication.run(Springboot310ConfigBindToBeanApplication.class, args);
	}

}
