package com.qinghua.springboot;

import com.qinghua.springboot.bean.User;
import com.qinghua.springboot.service.UserService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Springboot305JunitApplication {

	// 在没有使用junit的情况下，我们可以通过main方法来测试我们的代码
	public static void main(String[] args) {
		ConfigurableApplicationContext applicationContext = SpringApplication.run(Springboot305JunitApplication.class, args);
		UserService userService = applicationContext.getBean("userService", UserService.class);
		User user = userService.findUser();
		System.out.println(user);

		applicationContext.close();
	}

}
